apiVersion: batch/v1
kind: CronJob
metadata:
  name: app-mercado-livre-cron
spec:
  schedule: "0 20 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: app-mercado-livre
            image: tatchisabato/app_mercado_livre:latest
            imagePullPolicy: Always
          restartPolicy: OnFailure
