version: 2

sources:
  - name: raw_data
    description: "This source contains raw data tables used in the project."
    tables:
      - name: raw_scraped_data_source
        description: "Table containing raw web scraping data."
        columns:
          - name: product_link
            description: "The URL to the product's page on the e-commerce website."
          - name: product_image
            description: "The URL to the product's image."
          - name: product_title
            description: "The title or name of the product."
          - name: previous_price
            description: "The previous listed price of the product."
          - name: current_price
            description: "The current listed price of the product."
          - name: discount
            description: "The discount offered on the product, if any."
          - name: installments
            description: "The installment plan for the product, showing how many payments and the amount per payment."
          - name: seller
            description: "The name of the seller offering the product."

models:
  - name: scraped_products
    description: "This model contains the results of the web scraping process, including product details such as pricing, discounts, and seller information."
    columns:
      - name: product_link
        description: "The URL to the product's page on the e-commerce website."
        tests:
          - not_null
          - unique

      - name: product_image
        description: "The URL to the product's image."

      - name: product_title
        description: "The title or name of the product."
        tests:
          - not_null

      - name: previous_price
        description: "The previous listed price of the product."
        tests:
          - not_null

      - name: current_price
        description: "The current listed price of the product."
        tests:
          - not_null

      - name: discount
        description: "The discount offered on the product, if any."

      - name: installments
        description: "The installment plan for the product, showing how many payments and the amount per payment."

      - name: seller
        description: "The name of the seller offering the product."

      - name: inserted_at
        description: "The timestamp when the product record was inserted into the database."
        tests:
          - not_null

      - name: updated_at
        description: "The timestamp when the product record was last updated in the database."
        tests:
          - not_null
