version: 2

models:
  - name: scraped_products
    description: "Table containing product data scraped from e-commerce websites."
    columns:
      - name: product_id
        description: "Unique product identifier."
        tests:
          - not_null
          - unique
      - name: product_link
        description: "URL of the product."
        tests:
          - not_null
          - unique
      - name: product_image
        description: "URL of the product image."
        tests:
          - not_null
      - name: product_title
        description: "Title of the product."
        tests:
          - not_null
      - name: previous_price
        description: "Previous price of the product, if available."
        tests:
          - not_null
      - name: current_price
        description: "Current price of the product."
        tests:
          - not_null
          - dbt_utils.expression_is_true:
              expression: "current_price >= 0"
      - name: discount
        description: "Discount information for the product, if available."
        tests:
          - not_null
      - name: installments
        description: "Installments information for the product, if available."
        tests:
          - not_null
      - name: seller
        description: "Seller information for the product."
        tests:
          - not_null
          - unique
