name: FastApi CI Homolog - Docker

on:
  pull_request:
    branches:
      - master

jobs:

  test-docker:
    runs-on: ubuntu-latest
    environment: homolog

    steps:
    - uses: actions/checkout@v3

    - name: Install Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose

    - name: Build Docker Image
      run: |
        docker-compose build

    - name: Run Tests with Docker
      run: |
        docker-compose run --rm test
